before:
  hooks:
    - go mod download
    - apt-get update -y
    - apt-get install -y gcc-multilib

builds:
  - id: "chat-darwin-amd64"
    main: ./cmd/chat
    binary: chat
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w 
  - id: "chat-darwin-arm64"
    main: ./cmd/chat
    binary: chat
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w 
  - id: "chat-linux-amd64"
    main: ./cmd/chat
    binary: chat
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -extldflags "-static"
  - id: "chat-linux-i386"
    main: ./cmd/chat
    binary: chat
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - 386
    flags:
      - -tags=cgo -m32
    ldflags:
      - -s -w -extldflags "-static"
  - id: "chat-linux-armhf"
    main: ./cmd/chat
    binary: chat
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/armhf
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -extldflags "-static"
  - id: "chat-linux-arm64"
    main: ./cmd/chat
    binary: chat
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -extldflags "-static"
  - id: "chat-windows-amd64"
    main: ./cmd/chat
    binary: chat
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe
    ldflags:
      - -s -w 
  - id: "chat-windows-arm64"
    main: ./cmd/chat
    binary: chat
    goos:
      - windows
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
    flags:
      - -tags=cgo
      - -buildmode=exe
    ldflags:
      - -s -w
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - chat-darwin-amd64
      - chat-darwin-arm64
      - chat-linux-amd64
      - chat-linux-arm64
      - chat-linux-armhf
      - chat-linux-i386
      - chat-windows-amd64
      - chat-windows-arm64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
snapshot:
  name_template: "{{ .Tag }}-next"
